config/routes.rb
EFG::Application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => "sessions",
    :passwords => "passwords"
  }

  root to: 'dashboard#show'

  get 'healthcheck' => 'healthcheck#index'

  namespace :help do
    resource :ask_an_expert, controller: :ask_an_expert, only: [:create, :new]
    resource :ask_cfe, controller: :ask_cfe, only: [:create, :new]
  end

  resources :expert_users

  resources :lenders do
    member do
      post :activate
      post :deactivate
    end

    resources :lender_experts, only: :index

    resources :lending_limits do
      member do
        post :activate
        post :deactivate
      end
    end

    with_options only: [:index, :show, :new, :create, :edit, :update] do
      %w(lender_admins lender_users).each do |resource|
        resources resource do
          member do
            post :disable
            post :enable
            post :reset_password
            post :unlock
          end
        end
      end
    end
  end

  resources :loans, only: [:show] do
    collection do
      resource :eligibility_check, only: [:new, :create]
    end

    member do
      get :details
      get :audit_log
    end

    resource :eligibility_decision, only: [:show], controller: 'loan_eligibility_decisions' do
      member do
        post :email
      end
    end

    resource :cancel, only: [:new, :create], controller: 'loan_cancels'
    resource :entry, only: [:new, :create], controller: 'loan_entries' do
      member do
        get :complete
      end
    end
    resource :offer, only: [:new, :create], controller: 'loan_offers'
    resource :guarantee, only: [:new, :create], controller: 'loan_guarantees'
    resource :entry, only: [:new, :create], controller: 'loan_entries'
    resource :transferred_entry, only: [:new, :create], controller: 'transferred_loan_entries'
    resource :demand_to_borrower, only: [:new, :create], controller: 'loan_demand_to_borrowers'
    resource :repay, only: [:new, :create], controller: 'loan_repays'
    resource :no_claim, only: [:new, :create], controller: 'loan_no_claims'
    resource :demand_against_government, only: [:new, :create], controller: 'loan_demand_against_government'
    resource :premium_schedule, only: [:edit, :update, :show]
    resource :remove_guarantee, only: [:new, :create], controller: 'loan_remove_guarantees'
    resource :update_lending_limit, only: [:new, :create], controller: 'update_loan_lending_limits'

    resources :data_corrections, only: [:new, :create]
    resources :loan_changes, only: [:new, :create]
    resources :loan_modifications, only: [:index, :show]
    resources :recoveries, only: [:new, :create]

    resource :regenerate_schedule, only: [:new, :create]
  end

  resources :documents, only: [] do
    member do
      get :state_aid_letter
      get :information_declaration
    end

    collection do
      get :data_protection_declaration
    end
  end

  resources :loan_states, only: [:index, :show]

  resources :loan_alerts, only: :show

  with_options only: [:index, :show, :new, :create, :edit, :update] do

    %w(auditor_users cfe_admins cfe_users premium_collector_users).each do |resource|
      resources resource do
        member do
          post :disable
          post :enable
          post :reset_password
          post :unlock
        end
      end
    end

  end

  resource :search, only: [:show, :new], controller: :search do
    collection do
      get :lookup
    end
  end

  resources :invoices, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :realise_loans, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :loan_transfers, only: [:show, :new, :create]
  resources :legacy_loan_transfers, only: [:show, :new, :create]

  resource :loan_report, only: [:new, :create]

  resource :loan_audit_report, only: [:new, :create]

  resources :premium_schedule_reports, only: [:new, :create]

  resource :account_disabled, controller: 'account_disabled'

  resource :account_locked, controller: 'account_locked'

  resource :change_password, controller: 'change_password'

  resource :usernames_reminder, only: [:new, :create], controller: 'usernames_reminder'

  resources :phases, except: [:show, :destroy]

  resources :bulk_lending_limits, only: [:new, :create]
end

app/controllers/loan_entries_controller.rb
class LoanEntriesController < ApplicationController
  before_filter :verify_create_permission, only: [:new, :create]
  before_filter :load_loan
  rescue_from_incorrect_loan_state_error

  def new
    @loan_entry = LoanEntry.new(@loan)
  end

  def create
    @loan_entry = LoanEntry.new(@loan)
    @loan_entry.attributes = params[:loan_entry]
    @loan_entry.modified_by = current_user

    case params[:commit]
    when 'Save as Incomplete'
      @loan_entry.save_as_incomplete
      redirect_to loan_url(@loan_entry.loan)
    when 'State Aid Calculation'
      @loan_entry.save_as_incomplete
      redirect_to edit_loan_premium_schedule_url(@loan_entry.loan, redirect: 'loan_entry')
    else
      if @loan_entry.save
        if @loan_entry.complete?
          redirect_to complete_loan_entry_url(@loan_entry.loan)
        else
          redirect_to loan_url(@loan_entry.loan)
        end
      else
        render :new
      end
    end
  end

  def complete
  end

  private
  def verify_create_permission
    enforce_create_permission(LoanEntry)
  end

  def load_loan
    @loan = current_lender.loans.find(params[:loan_id])
  end

end

app/controllers/state_aid_calculation_variant/loan_entry.rb
class StateAidCalculationVariant::LoanEntry < StateAidCalculationVariant::Base
  def self.to_param
    'loan_entry'
  end

  def leave_state_aid_calculation_path(loan)
    new_loan_entry_path(loan)
  end
end

app/views/loan_entries/complete.html.erb
<%= breadcrumbs_for_loan(@loan) %>

<div class="page-header">
  <h1>Loan <%= @loan.reference %> has been entered</h1>
</div>

<p>Entry of information about the facility has now been completed and it meets the necessary criteria to obtain the guarantee.</p>

<p>In order to progress the facility, a Scheme Facility Letter should be sent to the Applicant. This Scheme Facility Letter should follow the format adopted by your organisation for this type of facility. In addition, the following information should be provided to the Applicant:</p>

<ul>
  <li>The Applicant's Premium Payment Schedule for the facility. This can be generated from the Summary page.</li>
  <li>A letter confirming the level of De Minimis State Aid attributable to the facility. (See <em>'Generate State Aid Letter'</em> below).</li>
  <li>The Information Declaration that contains all the information used to determine eligibility. (See <em>'View Information Declaration'</em> below).</li>
  <li>The <a href="/pdfs/direct_debit_mandate.pdf" class="pdf-download">Direct Debit mandate</a> which should be printed.</li>
</ul>

<div class="form-actions">
  <%= link_to 'View Loan Summary', loan_path(@loan), class: 'btn' %>
  <%= link_to_information_declaration(@loan) %>
  <%= link_to_state_aid_letter(@loan) %>
  <%= link_to "View Direct Debit Mandate", "/pdfs/direct_debit_mandate.pdf", class: 'btn btn-info pdf-download' %>
</div>

app/views/loan_entries/new.html.erb
<%= breadcrumbs_for_loan(@loan) %>

<div class="page-header">
  <h1>Loan Entry</h1>
</div>

<p>From this page you can complete the application for the Government Guarantee. Before entering any further information on this page, the lender must have received the <%= link_to "Data Protection and Disclosure Declaration", data_protection_declaration_documents_path(format: :pdf), class: 'pdf-download' %> signed by the Application and checked the box by way of confirmation.</p>
<p>Following completion of the Business Facility and Lender sections of the application a decision will be returned and if agreed the application can be progress to 'Offered'.</p>
<p>Please note that all the information within Facility Entry can be revised, however before progressing to Offered the information must represent the final terms agreed with the Applicant as it cannot subsequently be changed.</p>

<hr>

<%= simple_form_for(@loan_entry, url: loan_entry_path(@loan), html: {class: 'form-horizontal form-loan-entry'}) do |f| %>
  <%= field_set_tag do %>
    <%= f.input :declaration_signed, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
  <% end %>

  <%= field_set_tag 'Business' do %>
    <%= f.input :business_name, as: :string %>
    <%= f.input :trading_name, as: :string %>
    <%= f.input :legal_form_id, as: :select, collection: LegalForm.all, prompt: 'Please select' %>
    <%= f.input :company_registration, as: :string %>
    <%= f.input :turnover, as: :currency %>
    <%= f.input :trading_date, as: :quick_date %>
    <%= f.input :postcode, as: :string %>
    <%= f.input :sortcode, as: :string %>
  <% end %>

  <%= field_set_tag 'Loan' do %>
    <%= f.input :lender_reference %>
    <%= f.input :amount, as: :currency %>
    <%= f.input :lending_limit_id, as: :select, collection: @loan_entry.lender.lending_limits.where(id: @loan_entry.lending_limit_id) %>
    <%= f.input :repayment_duration, as: :duration %>
    <%= f.input :repayment_frequency_id, as: :select, collection: RepaymentFrequency.all, prompt: 'Please select', input_html: { class: 'input-xxlarge' } %>
    <%= simple_form_row t('simple_form.labels.loan_entry.sic_code'), @loan.sic_code %>
    <%= simple_form_row t('simple_form.labels.loan_entry.sic_desc'), @loan.sic_desc %>
    <%= f.input :reason_id, as: :select, collection: LoanReason.active, prompt: 'Please select', input_html: { class: 'input-xxlarge' } %>
    <%= f.input :interest_rate_type_id, as: :radio_buttons, collection: InterestRateType.all, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :interest_rate, as: :string %>
    <%= f.input :fees, as: :currency %>
    <%= f.input :previous_borrowing, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :state_aid, as: :state_aid %>
    <%= f.input :state_aid_is_valid, as: :boolean %>
    <%= f.input :private_residence_charge_required, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :personal_guarantee_required, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
  <% end %>

  <%= field_set_tag 'EFG Lending Type' do %>

    <%= f.input :loan_category_id, as: :select, collection: LoanCategory.all, prompt: 'Please select', input_html: { class: 'input-xxlarge' } %>

    <% for_loan_in_categories(@loan_entry, 2) do %>
      <%= f.input :loan_security_types,
                  as: :select,
                  collection: LoanSecurityType.all,
                  input_html: { class: 'input-xxlarge', multiple: true },
                  selected: @loan.loan_security_types.collect(&:id) %>

      <%= f.input :security_proportion, as: :percentage %>
    <% end %>

    <% for_loan_in_categories(@loan_entry, 3) do %>
      <%= f.input :original_overdraft_proportion, as: :percentage %>
    <% end %>

    <% for_loan_in_categories(@loan_entry, 3, 4) do %>
      <%= f.input :refinance_security_proportion, as: :percentage %>
    <% end %>

    <% for_loan_in_categories(@loan_entry, 4) do %>
      <%= f.input :current_refinanced_amount, as: :currency %>
      <%= f.input :final_refinanced_amount, as: :currency %>
    <% end %>

    <% for_loan_in_categories(@loan_entry, 5) do %>
      <%= f.input :overdraft_limit, as: :currency %>
      <%= f.input :overdraft_maintained, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <% end %>

    <% for_loan_in_categories(@loan_entry, 6) do %>
      <%= f.input :invoice_discount_limit, as: :currency %>
      <%= f.input :debtor_book_coverage, as: :percentage %>
      <%= f.input :debtor_book_topup, as: :percentage %>
    <% end %>

  <% end %>

  <%= field_set_tag 'Lender' do %>
    <%= f.input :viable_proposition, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :would_you_lend, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :collateral_exhausted, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :generic1, as: :string %>
    <%= f.input :generic2, as: :string %>
    <%= f.input :generic3, as: :string %>
    <%= f.input :generic4, as: :string %>
    <%= f.input :generic5, as: :string %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, value: 'Submit', class: 'btn-primary', data: { 'disable-with' => 'Submitting...' } %>
    <%= f.button :submit, value: 'Save as Incomplete', class: 'btn-secondary', data: { 'disable-with' => 'Submitting...' } %>
  </div>
<% end %>