config/routes.rb
EFG::Application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => "sessions",
    :passwords => "passwords"
  }

  root to: 'dashboard#show'

  get 'healthcheck' => 'healthcheck#index'

  namespace :help do
    resource :ask_an_expert, controller: :ask_an_expert, only: [:create, :new]
    resource :ask_cfe, controller: :ask_cfe, only: [:create, :new]
  end

  resources :expert_users

  resources :lenders do
    member do
      post :activate
      post :deactivate
    end

    resources :lender_experts, only: :index

    resources :lending_limits do
      member do
        post :activate
        post :deactivate
      end
    end

    with_options only: [:index, :show, :new, :create, :edit, :update] do
      %w(lender_admins lender_users).each do |resource|
        resources resource do
          member do
            post :disable
            post :enable
            post :reset_password
            post :unlock
          end
        end
      end
    end
  end

  resources :loans, only: [:show] do
    collection do
      resource :eligibility_check, only: [:new, :create]
    end

    member do
      get :details
      get :audit_log
    end

    resource :eligibility_decision, only: [:show], controller: 'loan_eligibility_decisions' do
      member do
        post :email
      end
    end

    resource :cancel, only: [:new, :create], controller: 'loan_cancels'
    resource :entry, only: [:new, :create], controller: 'loan_entries' do
      member do
        get :complete
      end
    end
    resource :offer, only: [:new, :create], controller: 'loan_offers'
    resource :guarantee, only: [:new, :create], controller: 'loan_guarantees'
    resource :entry, only: [:new, :create], controller: 'loan_entries'
    resource :transferred_entry, only: [:new, :create], controller: 'transferred_loan_entries'
    resource :demand_to_borrower, only: [:new, :create], controller: 'loan_demand_to_borrowers'
    resource :repay, only: [:new, :create], controller: 'loan_repays'
    resource :no_claim, only: [:new, :create], controller: 'loan_no_claims'
    resource :demand_against_government, only: [:new, :create], controller: 'loan_demand_against_government'
    resource :premium_schedule, only: [:edit, :update, :show]
    resource :remove_guarantee, only: [:new, :create], controller: 'loan_remove_guarantees'
    resource :update_lending_limit, only: [:new, :create], controller: 'update_loan_lending_limits'

    resources :data_corrections, only: [:new, :create]
    resources :loan_changes, only: [:new, :create]
    resources :loan_modifications, only: [:index, :show]
    resources :recoveries, only: [:new, :create]

    resource :regenerate_schedule, only: [:new, :create]
  end

  resources :documents, only: [] do
    member do
      get :state_aid_letter
      get :information_declaration
    end

    collection do
      get :data_protection_declaration
    end
  end

  resources :loan_states, only: [:index, :show]

  resources :loan_alerts, only: :show

  with_options only: [:index, :show, :new, :create, :edit, :update] do

    %w(auditor_users cfe_admins cfe_users premium_collector_users).each do |resource|
      resources resource do
        member do
          post :disable
          post :enable
          post :reset_password
          post :unlock
        end
      end
    end

  end

  resource :search, only: [:show, :new], controller: :search do
    collection do
      get :lookup
    end
  end

  resources :invoices, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :realise_loans, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :loan_transfers, only: [:show, :new, :create]
  resources :legacy_loan_transfers, only: [:show, :new, :create]

  resource :loan_report, only: [:new, :create]

  resource :loan_audit_report, only: [:new, :create]

  resources :premium_schedule_reports, only: [:new, :create]

  resource :account_disabled, controller: 'account_disabled'

  resource :account_locked, controller: 'account_locked'

  resource :change_password, controller: 'change_password'

  resource :usernames_reminder, only: [:new, :create], controller: 'usernames_reminder'

  resources :phases, except: [:show, :destroy]

  resources :bulk_lending_limits, only: [:new, :create]
end

app/models/eligibility_check.rb
class EligibilityCheck

  def initialize(loan)
    @loan = loan
    @errors = ActiveModel::Errors.new(loan)
    run_checks
  end

  attr_reader :loan, :errors

  def eligible?
    errors.empty?
  end

  def reasons
    errors.messages.values.flatten
  end

  private
  def run_checks
    add_error(:viable_proposition) unless loan.viable_proposition?
    add_error(:would_you_lend) unless loan.would_you_lend?
    add_error(:collateral_exhausted) unless loan.collateral_exhausted?
    add_error(:amount) unless loan.amount.between?(Money.new(1_000_00), Money.new(1_000_000_00))
    add_error(:previous_borrowing) unless loan.previous_borrowing?
    add_error(:private_residence_charge_required) if loan.private_residence_charge_required?
    add_error(:sic_code) unless loan.sic_eligible?
    add_error(:trading_date) if loan.trading_date > Date.today.advance(months: 6)
    check_repayment_duration
  end

  def add_error(attribute)
    errors.add(attribute, :invalid, message: I18n.translate("eligibility_check.attributes.#{attribute}.invalid"))
  end

  def check_repayment_duration
    repayment_duration = RepaymentDuration.new(loan)
    unless loan.repayment_duration.total_months.between?(repayment_duration.min_months, repayment_duration.max_months)
      add_error(:repayment_duration)
    end
  end

end

app/controllers/eligibility_checks_controller.rb
class EligibilityChecksController < ApplicationController
  before_filter :verify_create_permission, only: [:new, :create]

  def new
    @loan = current_lender.loans.new
    @loan_eligibility_check = LoanEligibilityCheck.new(@loan)
  end

  def create
    @loan = current_lender.loans.new
    @loan_eligibility_check = LoanEligibilityCheck.new(@loan)
    @loan_eligibility_check.attributes = params[:loan_eligibility_check]
    @loan_eligibility_check.created_by = current_user
    @loan_eligibility_check.modified_by = current_user

    # all new loans belong to EFG scheme
    @loan_eligibility_check.loan_scheme = Loan::EFG_SCHEME
    @loan_eligibility_check.loan_source = Loan::SFLG_SOURCE

    if @loan_eligibility_check.save
      redirect_to loan_eligibility_decision_url(@loan_eligibility_check.loan)
    else
      render :new
    end
  end

  private
  def verify_create_permission
    enforce_create_permission(LoanEligibilityCheck)
  end
end

app/views/eligibility_checks/new.html.erb
<%= breadcrumbs %>

<div class="page-header">
  <h1>Check Eligibility</h1>
</div>

<%= simple_form_for(@loan_eligibility_check, url: eligibility_check_path, html: {class: 'form-horizontal form-eligibility-check'}) do |f| %>
  <%= field_set_tag 'Declaration by Lender' do %>
    <%= f.input :viable_proposition, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :would_you_lend, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :collateral_exhausted, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
  <% end %>

  <%= field_set_tag 'About the Borrower and Their Facility' do %>
    <%= f.input :amount, as: :currency %>
    <%= f.input :lending_limit_id, as: :select, collection: @loan_eligibility_check.lender.current_lending_limits, prompt: 'Please select' %>
    <%= f.input :repayment_duration, as: :duration %>
    <%= f.input :turnover, as: :currency %>
    <%= f.input :trading_date, as: :quick_date %>
    <%= f.input :sic_code, as: :sic_code, collection: SicCode.active, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :loan_category_id, as: :select, collection: LoanCategory.all, prompt: 'Please select', input_html: { class: 'input-xxlarge' } %>
    <%= f.input :reason_id, as: :select, collection: LoanReason.active, prompt: 'Please select', input_html: { class: 'input-xxlarge' } %>
    <%= f.input :previous_borrowing, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :private_residence_charge_required, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
    <%= f.input :personal_guarantee_required, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, 'Check', class: 'btn-primary', data: { 'disable-with' => 'Submitting...' } %>
  </div>
<% end %>