config/routes.rb
EFG::Application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => "sessions",
    :passwords => "passwords"
  }

  root to: 'dashboard#show'

  get 'healthcheck' => 'healthcheck#index'

  namespace :help do
    resource :ask_an_expert, controller: :ask_an_expert, only: [:create, :new]
    resource :ask_cfe, controller: :ask_cfe, only: [:create, :new]
  end

  resources :expert_users

  resources :lenders do
    member do
      post :activate
      post :deactivate
    end

    resources :lender_experts, only: :index

    resources :lending_limits do
      member do
        post :activate
        post :deactivate
      end
    end

    with_options only: [:index, :show, :new, :create, :edit, :update] do
      %w(lender_admins lender_users).each do |resource|
        resources resource do
          member do
            post :disable
            post :enable
            post :reset_password
            post :unlock
          end
        end
      end
    end
  end

  resources :loans, only: [:show] do
    collection do
      resource :eligibility_check, only: [:new, :create]
    end

    member do
      get :details
      get :audit_log
    end

    resource :eligibility_decision, only: [:show], controller: 'loan_eligibility_decisions' do
      member do
        post :email
      end
    end

    resource :cancel, only: [:new, :create], controller: 'loan_cancels'
    resource :entry, only: [:new, :create], controller: 'loan_entries' do
      member do
        get :complete
      end
    end
    resource :offer, only: [:new, :create], controller: 'loan_offers'
    resource :guarantee, only: [:new, :create], controller: 'loan_guarantees'
    resource :entry, only: [:new, :create], controller: 'loan_entries'
    resource :transferred_entry, only: [:new, :create], controller: 'transferred_loan_entries'
    resource :demand_to_borrower, only: [:new, :create], controller: 'loan_demand_to_borrowers'
    resource :repay, only: [:new, :create], controller: 'loan_repays'
    resource :no_claim, only: [:new, :create], controller: 'loan_no_claims'
    resource :demand_against_government, only: [:new, :create], controller: 'loan_demand_against_government'
    resource :premium_schedule, only: [:edit, :update, :show]
    resource :remove_guarantee, only: [:new, :create], controller: 'loan_remove_guarantees'
    resource :update_lending_limit, only: [:new, :create], controller: 'update_loan_lending_limits'

    resources :data_corrections, only: [:new, :create]
    resources :loan_changes, only: [:new, :create]
    resources :loan_modifications, only: [:index, :show]
    resources :recoveries, only: [:new, :create]

    resource :regenerate_schedule, only: [:new, :create]
  end

  resources :documents, only: [] do
    member do
      get :state_aid_letter
      get :information_declaration
    end

    collection do
      get :data_protection_declaration
    end
  end

  resources :loan_states, only: [:index, :show]

  resources :loan_alerts, only: :show

  with_options only: [:index, :show, :new, :create, :edit, :update] do

    %w(auditor_users cfe_admins cfe_users premium_collector_users).each do |resource|
      resources resource do
        member do
          post :disable
          post :enable
          post :reset_password
          post :unlock
        end
      end
    end

  end

  resource :search, only: [:show, :new], controller: :search do
    collection do
      get :lookup
    end
  end

  resources :invoices, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :realise_loans, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :loan_transfers, only: [:show, :new, :create]
  resources :legacy_loan_transfers, only: [:show, :new, :create]

  resource :loan_report, only: [:new, :create]

  resource :loan_audit_report, only: [:new, :create]

  resources :premium_schedule_reports, only: [:new, :create]

  resource :account_disabled, controller: 'account_disabled'

  resource :account_locked, controller: 'account_locked'

  resource :change_password, controller: 'change_password'

  resource :usernames_reminder, only: [:new, :create], controller: 'usernames_reminder'

  resources :phases, except: [:show, :destroy]

  resources :bulk_lending_limits, only: [:new, :create]
end

app/controllers/loan_transfers_controller.rb
class LoanTransfersController < ApplicationController
  before_filter :verify_create_permission

  def show
    @loan = current_lender.loans.find(params[:id])
  end

  def new
    @loan_transfer = LoanTransfer::Sflg.new(Loan.new)
  end

  def create
    @loan_transfer = LoanTransfer::Sflg.new(Loan.new)
    @loan_transfer.attributes = params[:loan_transfer_sflg]
    @loan_transfer.lender = current_lender
    @loan_transfer.modified_by = current_user

    if @loan_transfer.save
      redirect_to loan_transfer_url(@loan_transfer.new_loan)
    else
      render :new
    end
  end

  private

  def verify_create_permission
    enforce_create_permission(LoanTransfer::Sflg)
  end

end

app/views/loan_transfers/new.html.erb
<%= breadcrumbs %>

<div class="page-header">
  <h1>Transfer a Loan</h1>
</div>

<p>From this page you can transfer loans from another approved SFLG lender.</p>

<p>(Tip. The details about the loan to be transferred can be obtained from the customer copy of the Scheme Facility Letter and Information Declaration).</p>

<hr>

<%= simple_form_for(@loan_transfer, url: loan_transfers_path, html: { class: 'form-horizontal form-loan-transfer' }) do |f| %>

  <%= render_errors_on_base(f.object.errors) %>

  <%= field_set_tag 'Please supply the following details about the loan to be transferred:' do %>

    <%= f.input :reference %>
    <%= f.input :amount, as: :currency %>
    <%= f.input :facility_letter_date, as: :quick_date %>

  <% end %>

  <%= field_set_tag 'And these details about the new loan:' do %>

    <%= f.input :new_amount, as: :currency %>
    <%= f.input :declaration_signed, as: :radio_buttons, wrapper_html: {class: 'radio-buttons-inline'} %>

  <% end %>

  <div class="form-actions">
    <%= f.button :submit, value: 'Transfer Loan', class: 'btn-primary', data: { 'disable-with' => 'Submitting...' } %>
  </div>
<% end %>

app/views/loan_transfers/show.html.erb
<%= breadcrumbs(
  link_to('Transfer a Loan', new_loan_transfer_path)
) %>

<div class="page-header">
  <h1>Loan Transfer Summary</h1>
</div>

<p>This page provides confirmation that the loan has been transferred.</p>

<p>You should proceed to enter the new details in Loan entry.</p>

<%= link_to('Loan Entry', new_loan_transferred_entry_path(@loan), class: 'btn') %>