config/routes.rb
EFG::Application.routes.draw do
  devise_for :users, :controllers => {
    :sessions => "sessions",
    :passwords => "passwords"
  }

  root to: 'dashboard#show'

  get 'healthcheck' => 'healthcheck#index'

  namespace :help do
    resource :ask_an_expert, controller: :ask_an_expert, only: [:create, :new]
    resource :ask_cfe, controller: :ask_cfe, only: [:create, :new]
  end

  resources :expert_users

  resources :lenders do
    member do
      post :activate
      post :deactivate
    end

    resources :lender_experts, only: :index

    resources :lending_limits do
      member do
        post :activate
        post :deactivate
      end
    end

    with_options only: [:index, :show, :new, :create, :edit, :update] do
      %w(lender_admins lender_users).each do |resource|
        resources resource do
          member do
            post :disable
            post :enable
            post :reset_password
            post :unlock
          end
        end
      end
    end
  end

  resources :loans, only: [:show] do
    collection do
      resource :eligibility_check, only: [:new, :create]
    end

    member do
      get :details
      get :audit_log
    end

    resource :eligibility_decision, only: [:show], controller: 'loan_eligibility_decisions' do
      member do
        post :email
      end
    end

    resource :cancel, only: [:new, :create], controller: 'loan_cancels'
    resource :entry, only: [:new, :create], controller: 'loan_entries' do
      member do
        get :complete
      end
    end
    resource :offer, only: [:new, :create], controller: 'loan_offers'
    resource :guarantee, only: [:new, :create], controller: 'loan_guarantees'
    resource :entry, only: [:new, :create], controller: 'loan_entries'
    resource :transferred_entry, only: [:new, :create], controller: 'transferred_loan_entries'
    resource :demand_to_borrower, only: [:new, :create], controller: 'loan_demand_to_borrowers'
    resource :repay, only: [:new, :create], controller: 'loan_repays'
    resource :no_claim, only: [:new, :create], controller: 'loan_no_claims'
    resource :demand_against_government, only: [:new, :create], controller: 'loan_demand_against_government'
    resource :premium_schedule, only: [:edit, :update, :show]
    resource :remove_guarantee, only: [:new, :create], controller: 'loan_remove_guarantees'
    resource :update_lending_limit, only: [:new, :create], controller: 'update_loan_lending_limits'

    resources :data_corrections, only: [:new, :create]
    resources :loan_changes, only: [:new, :create]
    resources :loan_modifications, only: [:index, :show]
    resources :recoveries, only: [:new, :create]

    resource :regenerate_schedule, only: [:new, :create]
  end

  resources :documents, only: [] do
    member do
      get :state_aid_letter
      get :information_declaration
    end

    collection do
      get :data_protection_declaration
    end
  end

  resources :loan_states, only: [:index, :show]

  resources :loan_alerts, only: :show

  with_options only: [:index, :show, :new, :create, :edit, :update] do

    %w(auditor_users cfe_admins cfe_users premium_collector_users).each do |resource|
      resources resource do
        member do
          post :disable
          post :enable
          post :reset_password
          post :unlock
        end
      end
    end

  end

  resource :search, only: [:show, :new], controller: :search do
    collection do
      get :lookup
    end
  end

  resources :invoices, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :realise_loans, only: [:show, :new, :create] do
    collection do
      post :select_loans
    end
  end

  resources :loan_transfers, only: [:show, :new, :create]
  resources :legacy_loan_transfers, only: [:show, :new, :create]

  resource :loan_report, only: [:new, :create]

  resource :loan_audit_report, only: [:new, :create]

  resources :premium_schedule_reports, only: [:new, :create]

  resource :account_disabled, controller: 'account_disabled'

  resource :account_locked, controller: 'account_locked'

  resource :change_password, controller: 'change_password'

  resource :usernames_reminder, only: [:new, :create], controller: 'usernames_reminder'

  resources :phases, except: [:show, :destroy]

  resources :bulk_lending_limits, only: [:new, :create]
end

app/models/loan_change.rb
class LoanChange < LoanModification
  validates_inclusion_of :change_type_id, in: %w(2 3 4 5 6 7 8 a), strict: true
  validate :validate_non_negative_amounts

  private
    def validate_non_negative_amounts
      errors.add(:amount_drawn, :not_be_negative) if amount_drawn && amount_drawn < 0
      errors.add(:lump_sum_repayment, :not_be_negative) if lump_sum_repayment && lump_sum_repayment < 0
    end
end

app/controllers/loan_changes_controller.rb
class LoanChangesController < ApplicationController
  TYPES = {
    'lump_sum_repayment' => LumpSumRepaymentLoanChange,
    'repayment_duration' => RepaymentDurationLoanChange,
    'reprofile_draws' => ReprofileDrawsLoanChange
  }

  before_filter :verify_create_permission
  before_filter :load_loan
  before_filter :load_presenter, only: [:new, :create]

  def index
  end

  def new
  end

  def create
    @presenter.attributes = params[:loan_change]
    @presenter.created_by = current_user

    if @presenter.save
      redirect_to loan_url(@loan)
    else
      render :new
    end
  end

  private
    def load_loan
      @loan = current_lender.loans.guaranteed.find(params[:loan_id])
    end

    def load_presenter
      klass = TYPES[params[:type]]

      if klass
        @presenter = klass.new(@loan)
      else
        redirect_to action: :index
      end
    end

    def verify_create_permission
      enforce_create_permission(LoanChange)
    end
end

app/helpers/loan_changes_helper.rb
module LoanChangesHelper

  def premium_schedule_hidden_fields(hash)
    if hash.is_a?(Hash)
      %w(
        premium_cheque_month
        initial_draw_amount
        repayment_duration
        initial_capital_repayment_holiday
        second_draw_amount
        second_draw_months
        third_draw_amount
        third_draw_months
        fourth_draw_amount
        fourth_draw_months
      ).collect do |field|
        hidden_field_tag "premium_schedule[#{field}]", hash[field.to_sym]
      end.join.html_safe
    end
  end

end

app/views/loan_changes/_lump_sum_repayment.html.erb
<%= simple_form_row 'Cumulative amount drawn against this facility prior to this change', @loan.cumulative_drawn_amount.format %>
<%= simple_form_row 'Cumulative amount repaid to this facility prior to this change', @loan.cumulative_lump_sum_amount.format %>

<%= f.input :lump_sum_repayment, as: :currency %>

app/views/loan_changes/_repayment_duration.html.erb
<%= simple_form_row 'Current maturity date', @loan.maturity_date.to_s(:screen) %>

<%= f.input :added_months, input_html: { class: 'input-mini' } %>

app/views/loan_changes/index.html.erb
<%= breadcrumbs_for_loan(@loan) %>

<div class="page-header">
  <h1>Change Loan</h1>
</div>

<p>From this page you can change the amount or terms of a facility (excluding the amount of the original facility or extending the term beyond ten years) and return a facility from 'Demand to Borrower' to 'Guaranteed'.</p>

<ul>
  <li><%= link_to('Extend / Reduce', new_loan_loan_change_path(@loan, type: 'repayment_duration')) %></li>
  <li><%= link_to('Lump Sum Repayment', new_loan_loan_change_path(@loan, type: 'lump_sum_repayment')) %></li>
  <li><%= link_to('Reprofile Draws', new_loan_loan_change_path(@loan, type: 'reprofile_draws')) %></li>
</ul>

app/views/loan_changes/new.html.erb
<%= breadcrumbs_for_loan(
  @loan,
  link_to('Change Facility', loan_loan_changes_path(@loan))
) %>

<div class="page-header">
  <h1>Change Facility</h1>
</div>

<p><span class="label label-info">INFORMATION</span> A new Premium Schedule will be generated from the information entered here.</p>

<hr>

<%= simple_form_for(@presenter, url: loan_loan_changes_path(@loan, type: params[:type]), html: { class: 'form-horizontal form-loan-change' }) do |f| %>
  <%= render_errors_on_base(f.object.errors) %>

  <%= f.input :date_of_change, as: :quick_date %>

  <%= simple_form_row 'Original loan amount', @loan.amount.format %>

  <%= render params[:type], f: f %>

  <%= field_set_tag 'Draw Information' do %>
    <%= simple_form_row 'Next quarterly Premium month due', @presenter.next_premium_cheque_month %>
    <%= f.input :initial_draw_amount, as: :currency %>
    <%= simple_form_row 'Outstanding loan term at the next quarterly Premium collection point', @presenter.repayment_duration_at_next_premium %>

    <hr>

    <%= f.input :initial_capital_repayment_holiday, input_html: { class: 'input-mini' } %>
    <%= f.input :second_draw_amount, as: :currency %>
    <%= f.input :second_draw_months, input_html: { class: 'input-mini' } %>
    <%= f.input :third_draw_amount, as: :currency %>
    <%= f.input :third_draw_months, input_html: { class: 'input-mini' } %>
    <%= f.input :fourth_draw_amount, as: :currency %>
    <%= f.input :fourth_draw_months, input_html: { class: 'input-mini' } %>
  <% end %>

  <div class="form-actions">
    <%= f.button :submit, value: 'Submit', class: 'btn-primary', data: { 'disable-with' => 'Submitting...' } %>
  </div>
<% end %>